### ISSUE TITLE
Add color scheme option for the spatial plot.

### ISSUE THREAD

**Issue by andrejadd** [WayneGitShell/GWSDAT#182]
1)     Choose colour scheme – keep existing, topo, terrain and grayscale.

2)     Choose max concentration (above which everything else is “>Max”)

3)     Choose number of levels.

**Comment by mrecos** [comment]
Hello! I was looking for places to help contribute and came across this issue. See [this commit](https://github.com/mrecos/GWSDAT/commit/46951584ab9aa821f97c0c56a6110021d1e848f8) on my fork. It is a pretty simple start, but may be in line with what you are looking for (see screenshot below). Is this a helpful avenue? Thanks!

![image](https://user-images.githubusercontent.com/7978067/55207534-f4859580-51b0-11e9-9616-e57eca3e0a1b.png)

**Comment by WayneBetws** [comment]
Thanks for the suggested contribution Matt. Another commonly requested enhancement is to be able to configure the colour key axis levels. Will hopefully incorporate this some point in the future.

**Comment by WayneGitShell** [comment]
Custom Colour key introduced in version 3.1
